// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"
)

type Quote struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	BusinessType string    `json:"business_type"`
	Contact      string    `json:"contact"`
	Plan         string    `json:"plan"`
	Message      string    `json:"message"`
	CreatedAt    time.Time `json:"created_at"`
}

type Subscriber struct {
	ID        int64     `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
