// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	AddSubscriber(ctx context.Context, email string) error
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
