// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotes.sql

package dbgen

import (
	"context"
)

const addSubscriber = `-- name: AddSubscriber :exec
INSERT INTO subscribers (email)
VALUES ($1)
ON CONFLICT (email) DO NOTHING
`

func (q *Queries) AddSubscriber(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, addSubscriber, email)
	return err
}

const createQuote = `-- name: CreateQuote :one
INSERT INTO quotes (name, business_type, contact, plan, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateQuoteParams struct {
	Name         string `json:"name"`
	BusinessType string `json:"business_type"`
	Contact      string `json:"contact"`
	Plan         string `json:"plan"`
	Message      string `json:"message"`
}

func (q *Queries) CreateQuote(ctx context.Context, arg CreateQuoteParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createQuote,
		arg.Name,
		arg.BusinessType,
		arg.Contact,
		arg.Plan,
		arg.Message,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
